<?php
return [
    'ADMIN_EMAIL' => 'admin@admin.com',
    'ADMIN_PCT' => 10,
    'commonErrorMessage' => 'Something went wrong please try again later.',
    'STATUS_CODE' => [
        'Ok' =>200,
        'CREATED' => 201,
        'BAD_REQUEST' => 400,
        'UNAUTHORIZED' => 401,
        'FORBIDDEN' => 403,
        'NOT_FOUND' => 404,
        'METHOD_NOT_ALLOWED' => 405,
        'CONFLICT' => 409,
        'LENGTH_REQUIRED' => 411,
        'PRECONDITION_FAILED' => 412,
        'TOO_MANY_REQUESTS' => 429,
        'INTERNAL_SERVER_ERROR' => 500,
        'SERVICE_UNAVAILABLE' => 503,
    ],
    'LOGO_WIDTH' => 128,
    'LOGO_HEIGHT' => 128,
    'EVENT_IMAGE_WIDTH' => 400,
    'EVENT_IMAGE_HEIGHT' => 400,
    'DUMMY_IMAGE_URL' => 'public/assets',
    'THUMBNAIL_PATH' => public_path('assets/uploads/thumbnails'),
    'THUMBNAIL_URL' => 'public/assets/uploads/thumbnails',
    'IMAGE_PATH' => public_path('assets/uploads/images'),
    'VIDEO_PATH' => public_path('assets/uploads/videos'),
    'IMAGE_URL' => 'public/assets/uploads/images',
    'VIDEO_URL' => 'public/assets/uploads/videos',
];
